### ISSUE TITLE
brenda-work forming bad requests?

### ISSUE THREAD

**Issue by ocheret** [jamesyonan/brenda#19]
I'm following along with the tutorial.  I've put my tar.gz on s3 and can see it.

I've set up a template...

[Propeller:Earth]563$ cat frame-template 
blender -b *.blend -F PNG -o $OUTDIR/frame_###### -s $START -e $END -j $STEP -t 0 -a

But trying to push work fails due to '"Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length".

[Propeller:Earth]564$ brenda-work status
[Propeller:Earth]565$ brenda-work reset
[Propeller:Earth]566$ brenda-work -T frame-template -e 360 push
Traceback (most recent call last):
  File "/Users/chuck/anaconda/bin/brenda-work", line 121, in <module>
    main()
  File "/Users/chuck/anaconda/bin/brenda-work", line 112, in main
    work.push(opts, args, conf)
  File "/Users/chuck/anaconda/lib/python2.7/site-packages/brenda/work.py", line 75, in push
    q = aws.create_sqs_queue(conf)
  File "/Users/chuck/anaconda/lib/python2.7/site-packages/brenda/aws.py", line 145, in create_sqs_queue
    return conn.create_queue(qname, visibility_timeout=visibility_timeout)
  File "/Users/chuck/anaconda/lib/python2.7/site-packages/boto/sqs/connection.py", line 95, in create_queue
    return self.get_object('CreateQueue', params, Queue)
  File "/Users/chuck/anaconda/lib/python2.7/site-packages/boto/connection.py", line 1188, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.SQSError: SQSError: 400 Bad Request
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidParameterValue</Code><Message>Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length</Message><Detail/></Error><RequestId>75e59a3c-c14f-57f7-8d3d-d745be8cf602</RequestId></ErrorResponse>

**Comment by ocheret** [comment]
My own mistake.  New to this.  I did not realize the naming restrictions for SQS queue names was different from S3 bucket names.  I had a '.' in my queue name.
