### ISSUE TITLE
 routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by robksawyer** [jamesyonan/brenda#21]
I'm on a retina Macbook pro running Yosemite and having an issue regarding Amazon certificates and getting Brenda setup.

I've run the `s3cmd --configure` and it has completed successfully, but I'm still unable to use `brenda-work`. See the output below for more details. It appears to be a certificate issue. I will say that I'm pretty new to EC2, so I could have the configuration wrong or something. Maybe I'm using the wrong values for the ACCESS and SECRET keys? I pulled these values from the Access Keys (Access Key ID and Secret Access Key) section of Your Security Credentials inside of the Amazon Web Services Console. Any ideas?

```
New settings:
  Access Key: [MYACCESSKEY]
  Secret Key: [MYSECRET]
  Encryption password:
  Path to GPG program: /usr/local/bin/gpg
  Use HTTPS protocol: False
  HTTP Proxy server name:
  HTTP Proxy server port: 0

Test access with supplied credentials? [Y/n] Y
Please wait...
Success. Your access key and secret key worked fine :-)

Now verifying that encryption works...
Success. Encryption and decryption worked fine :-)

Save settings? [y/N] Y
```

Now when running `brenda-run init`, I get the following:

```
Robs-MacBook-Pro:brenda robsawyer$ brenda-run init
Pushing ssh public key '/Users/robsawyer/.ssh/id_rsa.pub' to AWS under 'brenda' key pair.
Error creating ssh key pair [Errno 1] _ssl.c:490: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Creating AWS security group 'brenda'.
Error creating security group [Errno 1] _ssl.c:490: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Out of curiousity I tried `brenda-work status` and the following is happening.

```
Robs-MacBook-Pro:brenda robsawyer$ brenda-work status
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/bin/brenda-work", line 121, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.6/bin/brenda-work", line 114, in main
    work.status(opts, args, conf)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/brenda/work.py", line 84, in status
    q = aws.get_sqs_queue(conf)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/brenda/aws.py", line 153, in get_sqs_queue
    return get_sqs_conn_queue(conf)[0]
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/brenda/aws.py", line 150, in get_sqs_conn_queue
    return conn.get_queue(qname), conn
  File "/usr/local/lib/python2.7/site-packages/boto/sqs/connection.py", line 462, in get_queue
    return self.get_object('GetQueueUrl', params, Queue)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1192, in get_object
    response = self.make_request(action, params, path, verb)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
ssl.SSLError: [Errno 1] _ssl.c:490: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by robksawyer** [comment]
I think I've solved the problem. I checked my ~/.bash_profile and commented out the following. I then reinstalled python via brew, ran brew doctor, restarted the iTerm and now I get:

bash_profile nonsense:

```
# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
#export PATH

# Setting PATH for MacPython 2.6
# The orginal version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/2.6/bin:${PATH}"
#export PATH
```

Now I get:

```
Robs-MacBook-Pro:~ me$ brenda-run init
Pushing ssh public key '/Users/me/.ssh/id_rsa.pub' to AWS under 'brenda' key pair.
KeyPair:brenda
Creating AWS security group 'brenda'.
```

Seems like a good start.
