### ISSUE TITLE
Cannot import error when running brenda-work

### ISSUE THREAD

**Issue by PrismaPhonic** [jamesyonan/brenda#22]
seems to install fine, but I get a few errors trying to run brenda-work.  when running from normal user I get:

$ brenda-work
Traceback (most recent call last):
  File "/usr/bin/brenda-work", line 20, in <module>
    from brenda import config, work, aws, version
ImportError: cannot import name 'config'

When I run with sudo I get:

$ sudo brenda-work
Traceback (most recent call last):
  File "/usr/bin/brenda-work", line 20, in <module>
    from brenda import config, work, aws, version
  File "/usr/lib/python3.4/site-packages/brenda/work.py", line 79
    print task,
             ^
SyntaxError: Missing parentheses in call to 'print'

It seems as though the syntax error is related to changes in Python 3.  Not sure what is causing the import error though.

**Comment by PrismaPhonic** [comment]
Alright, fixed this by running:

python2 setup.py install

instead of

python setup.py install.

Everything seems to work perfectly except for the step where I try to bit on c1.xlarge.  I get an error that I've exceeded the maximum spot instance request if I request more than one server.

**Comment by PrismaPhonic** [comment]
Alright, it appears the 1 server limit for spot is something they do for new accounts.

I can get as much ondemand as I want.  Here's the issue I run into with on demand.  It's not rendering anything!  

The output of my tail log for every server is this:

AttributeError: 'NoneType' object has no attribute 'read'
------- ec2-52-22-34-239.compute-1.amazonaws.com
    self.func()
  File "/usr/local/bin/brenda-node", line 105, in <lambda>
    func = lambda : node.run_tasks(opts, args, conf)
  File "/usr/local/lib/python2.7/dist-packages/brenda/node.py", line 342, in run_tasks
    error.retry(conf, task_loop)
  File "/usr/local/lib/python2.7/dist-packages/brenda/error.py", line 37, in retry
    ret = action()
  File "/usr/local/lib/python2.7/dist-packages/brenda/node.py", line 154, in task_loop
    task.msg = q.read()
AttributeError: 'NoneType' object has no attribute 'read'

Any ideas why this might be happening?
